#+Title: What is risk? Which decisions are the important ones?
#+Author: Britt Anderson
* Nucleus Accumbens and Risky Decisions
The source of these ideas was a recent article in [[doi:10.1038/nature17400][Nature]]. The article is very nice, but it got me thinking about how some scientific terms re-purpose everyday language, and how this might have lead to certain confusions. Also, some terms are so broad that several independent concepts can fall under the same label. When research addresses one of those concepts we occassionaly we feel we have learned something about all the others that fall under the same heading. 
* Risk

In every day discourse when we think of someone taking a risk, we often think there is a good chance they could fail, and that that failure could have important negative consequences. There is also often a sense that great gains are possible. When we talk about risk takers we might have in mind those who [[http://www.nytimes.com/2015/03/11/magazine/the-heart-stopping-climbs-of-alex-honnold.html?_r=0][climb cliffs without support]] or [[https://en.wikipedia.org/wiki/BASE_jumping][leap off mountains and paraglide down]]. This is not the technical definition of risk. It is not the way Zalocusky et al. use the term. For decision making research risk is often taken as the known uncertainty, the variance in the reward distribution. In their paper, Zalocusky et al exposed rats to a decision making environment in which average reward was the same, but the rats could either choose to press a lever with a small constant amount of sugar water or another risky lever that gave large rewards a quarter of the time, and smaller rewards otherwise. Their use of term risk is rigorous and clear, it is just not the way we use the word risk in our everyday discussions of decision making. The average reward of the base jumper is not the same as the chap sitting in the Chalet sipping chocolat chaud and watching. [[http://www.dailymail.co.uk/news/article-3493687/Leading-BASE-jumper-killed-instantly-leap-heavy-fog-10-000ft-mountain-Switzerland-goes-wrong.html][Even experienced base jumpers may die.]] People who engage in repetitive gambling frequently go broke. The risky decisions in our everyday life that motivate our interest in questions of risk and decisions in laboratories are not using the word "risk". At least it is not clear to me that the neurons driving some rats to choose a lever with high variance in sugar return while others choose a constant sugar reward are the same neurons that motivate some people to play slots to bankruptcy and others to jump off mountains risking death, though the language we use in the academic domain might lead many general readers to assume they were [fn:individual]


* Decision-making

This is another question about language. We refer to choosing who to marry or where to go to graduate school as making a decision. We also talk about a baseball pitcher deciding what pitch to throw as making a decision. Based on the language we use we might think we were describing the same "thing" in both cases, but are we? A professional starting baseball pitcher might throw 100 pitches in a game, and might pitch in 30 games a season. In between his practice is more of the same: deciding on a pitch, and then throwing that pitch. This seems quite similar to the repetitive, similar choices made by the rats in Zalocusky et al's experiment[fn:average]. 

Isn't this significantly different than the other types of decisions I listed? When choosing a mate there is no repetition. It is one and done. Even if you grow dissatisfied with your partner, leave them and choose another it is not the same decision - at least not in the way that repetitively choosing a lever for a sugar reward is. You are older. You are changed by the consequences of that choice. You might choose a mate more than once, but you are not making the same choice twice. At least it must be conceded the choices are not [[https://en.wikipedia.org/wiki/Independent_and_identically_distributed_random_variables][i.i.d.]] [fn:shackle]. 

Why should we assume decisions of the first, i.i.d., type are the same as the one-off life changing sort? The i.i.d. type are the one studied in laboratories with rats pushing levers and people playing [[doi:10.1371/journal.pone.0017798][empathy games]]. Are those studies informing us of the mechansims that underlie our decisions in the apparently one-off choices we have to make?

The answer I am usually given when I ask this question is that our one-off choices are similar too other choices we have made in the past. Choosing a mate is similar to choosing a prom date. It is similar to asking someone to the movies. It is similar to choosing a pet. And so on. The similarity differs, but they are enough alike that this decision history provides the shaping that leads to the preferences we express when selecting to whom, and whether, to propose. But that verbal argument does not persuade. The dimensionality of the space where decisions have to be mapped, be it neurophysiological (the voltage of everyone neuron in your brain at every picosecond of existence) or psychological (the day was gray, you were in a bad mood) though finite is likely to be very large. And such a space is likely to be very sparsely populated (the so-called curse of dimensionality). How are we to effectively measure similarity in such a space? To learn what is similiar? To even learn what dimensions of the space "matter" and for what kind of decisions? It doesn't seem too improbable to think that a few thousand repetitive lever pressess of a rat for sugar water end up "near-by" in this high dimensional space, but are those points near the points needed when the rat has to decide whether to fight another for dominance? How would we know?

This is not a critique of the paper. This is a critique of how we use the results from such papers. We are generally too incautious in our extrapolations. Just because a research article deals with "decision-making" does not mean we should generalize its findings to the types of decisions that most of us spend our lives agonizing over. Where are the similar decisions, and how many repetitions does one get when deciding "To be or not to be"? 


[fn:individual]Another claim in the article is that the rats showed individual differences. Some rats preferred the high variance lever and others the constant lever. But recall that each lever led to the same average return. Couldn't the two levers represent two equivalent local minima in the behavioral space? If so, might it not be that rats did not /initially/ posses intrinsic differences that led them to seek or avoid risk, but that some random variation led some rats to one fixed point and other rats to the other fixed point? The changes in neuronal activity then might have been the *result* of where they ended up, and not what led them there? Of course, this question is rather orthogonal to the point about language I am making above.
[fn:average]Though it is not clear that any sequence of choices by the pitcher would lead to the same average reward. Mighn't this be important?
[fn:shackle] I was led to this thinking by G.L.S. Shackle. See his [[http://www.cambridge.org/ca/academic/subjects/economics/history-economic-thought-and-methodology/decision-order-and-time-human-affairs-2nd-edition?format=PB][Decision, Order, and Time in Human Affairs.]]
