#+TITLE:       Org Pages Occult Art
#+AUTHOR:      Britt Anderson
#+EMAIL:       britt@uwaterloo.ca
#+DATE:        2016-02-19 Fri
#+URI:         /blog/%y/%m/%d/org-pages-occult-art
#+KEYWORDS:    org-page
#+TAGS:        org-page
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: the details of using org-pages
* Intro
In a prior [[file:blog/2016/02/16/static-sites-with-org-page/][post]] I described getting org-pages up and running. And that basically it was pretty smooth. However, getting org-pages to do what you want beyond the basic is not so smooth.

Unfortunately, there is limited documentation, and while the maintainter is very responsive, there is still a need to search the web and to look at source code. Here are a few useful sources that I have come across:
* Themes
If you want to change the theme or css make a frequent use of `(setq op/item-cache nil)` to clear cache variables used by org-pages when re-creating things. 

If you want to edit the themes you will need to edit the css and you will need to set some variables for this. The best instructions I found where [[http://heikkil.github.io/blog/2015/03/28/understanding-org-page/][here]]. Heikki does a nice job of walking through some of the pain points. It boils down to copying the themes directory from the org-pages source folder (which if you use melpa will be somewhere like =~/.emacs.d/elpa/org-pages-#########/themes/=). You then,

#+Begin_Src elisp :exports code :results silent
(setq op/theme-root-directory "<where-you-put-it>")
(setq op/theme '<what-you-called-it>)  ; mdo is the default
#+End_src

* Git
This is another tough point, at least for me, and is well covered by Heikki in his post. This is just a summary.

After you initiate things with `op/new-repository` make sure you are on the =source= branch. Then you can create a `op/new-post`. Answer the questions. Write your post. When you are done writing the post, /and before you preview you must *commit* your changes.  Then you can preview it with: `op/do-publication-and-preview-site`. That will whir for a bit and then it will put all the files in a temporary directory in your home directory. It will launch a simple emacs server and you can view the results in your browser. Once you have what you like, and if you have made changes, commit those changes (still on the source branch), and then `op/do-publication`. This will create all the html files on the master branch of your repo. You can manually push those to whereever, or you can let org-pages do it in the process of publishing. 

I found this tough, and a bit unforgiving, but that may well be because I am still learning non-trivial git at the same time. 

Once you get to this point, blog post 2, you are probably good to go, and have a work flow you can live with. Cheers.
